name: barter_x
description: Introducing Barter-X, the revolutionary mobile app that allows you
  to trade goods and services with your community without using any money. With
  Barter-X, you can list items you no longer need or services you can offer, and
  trade them for things you do need or want. Whether you're looking to de
  clutter your home, pick up a new hobby, or simply save money, Barter-X makes
  it easy to trade with others in your area.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  image_picker: ^0.8.7+4
  lottie: ^2.3.1
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  unicons: ^2.1.1

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/imgs/
    - assets/jsons/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: light
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
